%% Generated by the Erlang ASN.1 compiler. Version: 5.0.9
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module DNS-ASN1.

-ifndef(_DNS_ASN1_HRL_).
-define(_DNS_ASN1_HRL_, true).

-record('DSS-Sig', {
  r,
  s
}).

-endif. %% _DNS_ASN1_HRL_
